// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_dto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcAuthenticateSrvClient is the client API for RpcAuthenticateSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcAuthenticateSrvClient interface {
	CallRpcAuthenticateSrv(ctx context.Context, in *RpcAuthenticateRequest, opts ...grpc.CallOption) (*RpcAuthenticateReply, error)
}

type rpcAuthenticateSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcAuthenticateSrvClient(cc grpc.ClientConnInterface) RpcAuthenticateSrvClient {
	return &rpcAuthenticateSrvClient{cc}
}

func (c *rpcAuthenticateSrvClient) CallRpcAuthenticateSrv(ctx context.Context, in *RpcAuthenticateRequest, opts ...grpc.CallOption) (*RpcAuthenticateReply, error) {
	out := new(RpcAuthenticateReply)
	err := c.cc.Invoke(ctx, "/dto.RpcAuthenticateSrv/CallRpcAuthenticateSrv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcAuthenticateSrvServer is the server API for RpcAuthenticateSrv service.
// All implementations must embed UnimplementedRpcAuthenticateSrvServer
// for forward compatibility
type RpcAuthenticateSrvServer interface {
	CallRpcAuthenticateSrv(context.Context, *RpcAuthenticateRequest) (*RpcAuthenticateReply, error)
	mustEmbedUnimplementedRpcAuthenticateSrvServer()
}

// UnimplementedRpcAuthenticateSrvServer must be embedded to have forward compatible implementations.
type UnimplementedRpcAuthenticateSrvServer struct {
}

func (UnimplementedRpcAuthenticateSrvServer) CallRpcAuthenticateSrv(context.Context, *RpcAuthenticateRequest) (*RpcAuthenticateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallRpcAuthenticateSrv not implemented")
}
func (UnimplementedRpcAuthenticateSrvServer) mustEmbedUnimplementedRpcAuthenticateSrvServer() {}

// UnsafeRpcAuthenticateSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcAuthenticateSrvServer will
// result in compilation errors.
type UnsafeRpcAuthenticateSrvServer interface {
	mustEmbedUnimplementedRpcAuthenticateSrvServer()
}

func RegisterRpcAuthenticateSrvServer(s grpc.ServiceRegistrar, srv RpcAuthenticateSrvServer) {
	s.RegisterService(&RpcAuthenticateSrv_ServiceDesc, srv)
}

func _RpcAuthenticateSrv_CallRpcAuthenticateSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcAuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcAuthenticateSrvServer).CallRpcAuthenticateSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dto.RpcAuthenticateSrv/CallRpcAuthenticateSrv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcAuthenticateSrvServer).CallRpcAuthenticateSrv(ctx, req.(*RpcAuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcAuthenticateSrv_ServiceDesc is the grpc.ServiceDesc for RpcAuthenticateSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcAuthenticateSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dto.RpcAuthenticateSrv",
	HandlerType: (*RpcAuthenticateSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallRpcAuthenticateSrv",
			Handler:    _RpcAuthenticateSrv_CallRpcAuthenticateSrv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticate.proto",
}
